### ISSUE TITLE
结点内TreeNode<view>存在RecyclerView 的时候 ,setAdapter() 数据集很多的时候会卡

### ISSUE THREAD

**Issue by zhangle1** [TellH/RecyclerTreeView#11]
有没有什么好的解决办法
 @Override
    public void bindView(ContactsHolder holder, int position, TreeNode node) {
        holder.mContactsAdapter.clearAndSetData(contacts.getTxl());
        holder.mListener.setContacts(contacts);
        holder.mRv.removeOnItemTouchListener(holder.mListener);
}

**Comment by TellH** [comment]
数据集很多是有多少

**Comment by zhangle1** [comment]
已经减少了一点卡顿 notifyItemChange(position) !多谢
