### ISSUE TITLE
Permit locking of TreeNodes

### ISSUE THREAD

**Issue by instantiator** [TellH/RecyclerTreeView#13]
Sometimes it is important that some (or all) nodes not be collapsible (or not be expandable except under certain circumstances).

**Comment by TellH** [comment]
This feature was added in new version.
```
TreeNode<Dir> res = new TreeNode<>(new Dir("res"));
        nodes.add(res);
        res.addChild(
                new TreeNode<>(new Dir("layout")).lock() // lock this TreeNode
                        .addChild(new TreeNode<>(new File("activity_main.xml")))
                        .addChild(new TreeNode<>(new File("item_dir.xml")))
                        .addChild(new TreeNode<>(new File("item_file.xml")))
        );
```

**Comment by electronic321** [comment]
Hello TellH,
Nice library i would must say. Working as required till now.

I came across 2 issues which i would like to know.
1). In my scenario, i want to select any child & hide/remove the recyclerview after selection as required in my app flow. Tried for couple of hours now but could not get it done by using current methods provided. Can you please tell me that either it is possible with the current implementation or this thing requires further additional method to achieve this behaviour.

2). Plus i notice that if i select any number of childs (by childs, i mean **FILE** using checkbox/images) under any **DIRECTORY**, once i toggle that **DIRECTORY** and reopen it again, selected childs gets unchecked. Is there any way to overcome it.

Any help would be highly appreciate-able.
