### ISSUE TITLE
Setting list data by json..

### ISSUE THREAD

**Issue by ashokbg** [TellH/RecyclerTreeView#19]
Hi
Is it possible  to set list of Dir,File by  Json response  ? if possible how Json structure looks.

**Comment by TellH** [comment]
@ashokbg hi~ Actually I make it to display Dir and File by Json response in my project, you can check it out here. https://github.com/TellH/GitClub/blob/dev/app/src/main/java/tellh/com/gitclub/presentation/presenter/RepoSourcePresenter.java
