### ISSUE TITLE
Feature -> close other open paths when select to another node with animation

### ISSUE THREAD

**Issue by azimot** [TellH/RecyclerTreeView#2]
very great lib with RecyclerView , at first i thank you for sharing this great lib as opensource 

so i think it could be a feature for passing a boolean value in argument for closing behavior . 
for example ( boolean isAutoClosingNonSelected )

think in a directory project that have a lot of categories name and after user selected a node ( Category ) ,  in another View component i loading data of that Category so it's be nice to have behavior of closing unnecessary  nodes when user wants to open another node

is it possible to add it please ?

**Comment by TellH** [comment]
Thank your appreciation. In order to implement this effect, i add several methods to TreeViewAdapter. You can check it out with this code.
```
        adapter.setOnTreeNodeListener(new TreeViewAdapter.OnTreeNodeListener() {
            @Override
            public boolean onClick(TreeNode node, RecyclerView.ViewHolder holder) {
                if (!node.isLeaf()) {
                    //Update and toggle the node.
                    onToggle(!node.isExpand(), holder);
                    if (!node.isExpand())
                        adapter.collapseBrotherNode(node);
                }
                return false;
            }

            @Override
            public void onToggle(boolean isExpand, RecyclerView.ViewHolder holder) {
                DirectoryNodeBinder.ViewHolder dirViewHolder = (DirectoryNodeBinder.ViewHolder) holder;
                final ImageView ivArrow = dirViewHolder.getIvArrow();
                int rotateDegree = isExpand ? 90 : -90;
                ivArrow.animate().rotationBy(rotateDegree)
                        .start();
            }
        });
```
When opening a TreeNode, its brother nodes that was opening would be collapsed.
You can also collapse all TreeNodes. like:
```
                adapter.collapseAll();
```

Thanks for your feedback : )

**Comment by TellH** [comment]
DiffUtil is a very good tool 👍
