### ISSUE TITLE
你好，如何获取leaf的实体类（如你demo里的File对象）

### ISSUE THREAD

**Issue by JiangShuLiang** [TellH/RecyclerTreeView#21]
在recyclerview的行点击事件里，先判断是否是Leaf，如果是的话，我想获取这个File对象，请问要用 什么方法获取？先提前感谢了，btw，这个treeView做的很棒！点个赞！

**Comment by TellH** [comment]
谢谢你~ 其实做的还不够好的，比如还有很多issue没时间处理呢。
调用TreeNode的getContent方法即可拿到这个File对象
