### ISSUE TITLE
TreeViewAdapter setting unwanted paddings

### ISSUE THREAD

**Issue by mvp-sales** [TellH/RecyclerTreeView#3]
I noticed that the TreeViewAdapter on the onBindViewHolder method sets paddings that overwrites the paddings I set in the layout files, so I'm forced to set them manually at the bindView method in the view binders. 

Btw, thanks for your work, this library is the best among all Tree Views I've searched.

**Comment by TellH** [comment]
yes. The padding was taking itself as the point of reference.

**Comment by theMxyzptlk** [comment]
Could you remove those paddings then? I really don't think they are needed.
