### ISSUE TITLE
Manifest文件merge的时候会发生冲突

### ISSUE THREAD

**Issue by xvjianzhe** [TellH/RecyclerTreeView#7]
你好，在引用库的时候，如果app工程的Manifest文件中application标签下声明了下面的属性：
`android:allowBackup="true" 
 android:supportsRtl="true"`
那么如果主工程同样声明了对应的属性，但是值不相同时，在build的时候manifest文件merge会导致失败。
最好库的manifest文件中application标签声明成下面这样：
`<application />`
谢谢。

**Comment by TellH** [comment]
好的，谢谢
