### ISSUE TITLE
How to expand all item

### ISSUE THREAD

**Issue by ProFive** [TellH/RecyclerTreeView#9]
Hi Sir, 
How to expand all item when show list view ?

**Comment by vihuela** [comment]
private void expandAll(List<TreeNode> treeNode) {
        for (int i = 0; i < treeNode.size(); i++) {
            TreeNode item = treeNode.get(i);
            if (!item.isLeaf()) {
                item.toggle();
                expandAll(item.getChildList());
            }
        }
    }
